export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const SET_TOKEN_DETAILS_REQUEST = "SET_TOKEN_DETAILS_REQUEST";
export const SET_TOKEN_DETAILS_SUCCESS = "SET_TOKEN_DETAILS_SUCCESS";
export const SET_TOKEN_DETAILS_FAIL = "SET_TOKEN_DETAILS_FAIL";

export const CLEAR_TOKEN_DETAILS = "CLEAR_TOKEN_DETAILS";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
